name: Sync Upstream

on:
  schedule:
    - cron: "0 0,8,16 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/openfrontio/OpenFrontIO.git
          git fetch upstream

      - name: Sync whitelisted branches
        run: |
          BRANCHES_TO_SYNC="
          meta-v24
          v22.0
          v23
          "
          for branch in $BRANCHES_TO_SYNC; do
            if git show-ref --verify --quiet refs/remotes/upstream/$branch; then
              echo "Syncing $branch"
              git checkout -B "$branch" "upstream/$branch"
              git push origin "$branch" --force
            else
              echo "Branch $branch does not exist on upstream, skipping."
            fi
          done
